### ISSUE TITLE
Script error at line 34

### ISSUE THREAD

**Issue by Someguyman** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#1]
![20210124162457_1](https://user-images.githubusercontent.com/63017438/105644072-9cc61d00-5e61-11eb-806b-f86a52d6887e.jpg)

**Comment by Alriightyman** [comment]
What zone/act/time period?  I haven't seen this error yet.  Also, did you modify any of the scripts?

**Comment by Rubberduckycooly** [comment]
did you have any mods on? that can very much cause an error

**Comment by Rubberduckycooly** [comment]
closing this due to lack of info about the issue, and since it was likely user-error
