### ISSUE TITLE
This happened in Tidal Tempest Act 2

### ISSUE THREAD

**Issue by Lexkiz** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#23]
This appeared when i Selected Tidal Tempest Act 2 in Stage Select
![Screenshot_20221017-050944_RSDKv3](https://user-images.githubusercontent.com/115975198/196124069-cf98dc7f-ce22-417d-9453-142a60e7b547.jpg)
The heck happened?

**Comment by MegAmi24** [comment]
Already fixed, however you shouldn't be using the cleanup branch

**Comment by Lexkiz** [comment]
> Already fixed, however you shouldn't be using the cleanup branch

Wdym cleanup branch?

**Comment by Lexkiz** [comment]
@MegAmi24 wdym? I'm very confused rn 💀

**Comment by Lexkiz** [comment]
@MegAmi24 
> Already fixed, however you shouldn't be using the cleanup branch

What do you mean? I'm pretty confused rn.
