### ISSUE TITLE
Scripts ignoring "GameType" setting?

### ISSUE THREAD

**Issue by peter4432** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#24]
Not sure of this is a scripting bug or a decomp bug, but when I have GameType=0 in Settings, the Origins menu still loads when you press 'Start':
![image](https://user-images.githubusercontent.com/7239300/197214779-b4136664-77e3-441d-aaf3-a99bc7f7f721.png)

You can still access the orginal menu via the Dev menu.

Decomp exe is the **v3-windows-x64** verion from the **sega forever huh #374** autobuild.

Scripts used were downloaded from Cleanup branch on **Oct 21st**.

**Comment by MegAmi24** [comment]
You didn't enable TxtScripts, so it's still using the ByteCode.

**Comment by peter4432** [comment]
Still seeign same issue with TxtScripts setting set to true and having even removed the Bytecode Scripts folder from the Data directory so only scripts available should be the decomplied version:
![Issue_2](https://user-images.githubusercontent.com/7239300/197323822-98eea048-78dc-4dd4-b967-2d6f098aed27.png)

**Comment by peter4432** [comment]
Thanks. Now loading in PC mode.
