### ISSUE TITLE
Start screen display issue 

### ISSUE THREAD

**Issue by peter4432** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#25]
> Decomp exe is the v3-windows-x64 verion from the sega forever huh #374 autobuild.
> Scripts used were downloaded from Cleanup branch on Oct 21st.
> Data Source = Sonic Origins

> GameType=0
> FullScreen=false
> Borderless=false
> VSync=false
> ScalingMode=0
> WindowScale=3
> ScreenWidth=424
> RefreshRate=60

When when going to the title screens via most standard methods, there title screens has some white space showing on the right side:
![Issue_2](https://user-images.githubusercontent.com/7239300/197324419-7d166097-7b4b-4176-b8fb-6d32aada3313.png)

Only case so far where this issue doesn't occur is if you have **DevMenu=true** and use the **Start Game** option in the Dev Menu, which then has the Title screen show as expected.

**Comment by Leonx254** [comment]
All versions of the game have this mountain sprite in particular in a different position, if you want it to display correctly, you need to set gametype to 1 (origins)
I don't know why it gets fixed when starting from dev menu, but is not intended behaviour.
