### ISSUE TITLE
Amy and Knuckles crash

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#33]
I can select Amy and Knuckles in debug mode without the scripts folder enabled, however when I enable the folder, the game will crash upon trying to play as Amy or Knuckles. This is only problematic as the issue persists in the mod MegAmi's additions, which credits this decompilation, so I assume the problem has carried over from here to the mod. (I can't select amy or knuckles regardless of if I have the mod enabled, however if I enable just the mod, and not the scripts folder, I still can not select them. I can only select them without the scripts folder enabled)

I just want to be able to save the game whilst playing as amy or knuckles, which I can't do without the scripts folder's help, because origins version of cd lacks the save feature.

**Comment by MegAmi24** [comment]
Make sure you're using the scripts from the [origins-plus branch](https://github.com/Rubberduckycooly/Sonic-CD-2011-Script-Decompilation/tree/origins-plus).
