### ISSUE TITLE
No issue.  Just a question.

### ISSUE THREAD

**Issue by AaronStardust08** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#34]
So I don’t have an issue, but I do have a question about this decompilation.  For Sonic Origins Plus, do I just take the Scripts file itself and put it into the Sonic CD file, or do I take the files from within Scripts in Decompilation and put them in the Scripts file in the Sonic CD file?  Does my question make sense?

**Comment by MegAmi24** [comment]
I suggest reading [this tutorial](https://gamebanana.com/tuts/14111#H2_3) if you haven't already.

**Comment by AaronStardust08** [comment]
I did.  But that’s where I’m confused.

**Comment by MegAmi24** [comment]
You copy the Scripts folder itself, not just its contents. There's screenshots in the tutorial showing what it looks like when you do it correctly.

**Comment by AaronStardust08** [comment]
Oh.  Okay.  Thanks.  I just got confused on what the tutorial meant.

**Comment by AaronStardust08** [comment]
Do you know about the CD Voice Lines Fix mod?  I’m told I need this Decompilation in order to use it.  Is that true?

**Comment by MegAmi24** [comment]
Please do not ask questions related to mods here.

**Comment by AaronStardust08** [comment]
Why not?

**Comment by MegAmi24** [comment]
This repo is about the decompiled scripts. If you want mod support, please ask in the [REMS Discord server](https://dc.railgun.works/retroengine).
