### ISSUE TITLE
Script parsing failed

### ISSUE THREAD

**Issue by RanomRants** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#35]
So, whenever into a save file, I am given this error code. This is likely because I have mods on, (Sonic CD: Miracle Edition, and MegAmi's Additions in that order). I was just looking to see if there was any sort of fix to be able to play with the mods, but if there isn't right now, that's okay. 
![Screenshot 2024-02-21 183309](https://github.com/Rubberduckycooly/Sonic-CD-2011-Script-Decompilation/assets/129227653/d9f5896a-d3ac-4ed9-a213-0e6ef2dcba7a)

**Comment by RanomRants** [comment]
thank you. Can I have a link to the latest version?

**Comment by MegAmi24** [comment]
You're already on the correct repository. Just download the source code and copy over the Scripts folder from it.
