### ISSUE TITLE
Tidal Tempest white screen

### ISSUE THREAD

**Issue by The-maker-of-things** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#36]
Every time I try to load Tidal Tempest, it shows a white screen. the only way I'm able to see the level is pausing the game

**Comment by MegAmi24** [comment]
There's a mismatch between the version of CD you're playing and the `HardwareRenderer` setting in `settings.ini`. Set it to `false` if you're using a Steam or Origins datafile or `true` if you're using a Mobile one.
