### ISSUE TITLE
Tidal Tempest 1 Background Effects missing (Lack of mountain eruptions)

### ISSUE THREAD

**Issue by PimpUigi** [Rubberduckycooly/Sonic-CD-2011-Script-Decompilation#9]
Expected:
![image](https://user-images.githubusercontent.com/7344271/120936287-1c4bde80-c6d5-11eb-99f4-bfb4ab57dbf0.png)

Actual:
![image](https://user-images.githubusercontent.com/7344271/120936268-0c33ff00-c6d5-11eb-98a5-e72c407cdb5a.png)

**Comment by MegAmi24** [comment]
[Issue has been fixed](https://github.com/Rubberduckycooly/Sonic-CD-2011-Script-Decompilation/pull/10)
